services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    volumes:
      - ./src:/scripts
    entrypoint: ["k6", "run", "/scripts/BebasApps/1journey.js"]

volumes:
  influxdb:
  grafana:


###########################################################################

# version: '3.6'
# services:
#   influxdb:
#     image: influxdb:2.5.1-alpine
#     container_name: influxdb
#     restart: unless-stopped
#     networks:
#       - iotawatt_monitoring
#     ports:
#       - '8086:8086'
#     volumes:
#       - influxdb_data:/var/lib/influxdb2

#   grafana:
#     image: grafana/grafana
#     container_name: grafana-server
#     restart: unless-stopped
#     networks:
#       - iotawatt_monitoring
#     depends_on:
#       - influxdb
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin1234  #change the password
#       - GF_INSTALL_PLUGINS=
#     links:
#       - influxdb
#     ports:
#       - '43000:3000'
#     volumes:
#       - grafana_data:/var/lib/grafana
      
# networks:
#   iotawatt_monitoring:
 
# volumes:
#   grafana_data:
#   influxdb_data:

############################################################################

# version: '3.4'

# # networks:
# #   k6:
# #   grafana:

# services:
#   influxdb:
#     image: influxdb:1.8
# #    entrypoint: /bin/sh
# #    user: root
#     networks:
#       - k6
#       - grafana
#     ports:
#       - "8086:8086"
#     environment:
#       - INFLUXDB_DB=k6

#   grafana:
#     image: grafana/grafana:8.5.21
# #    entrypoint: /bin/sh
# #    user: root
#     networks:
#       - grafana
#     ports:
#       - "3000:3000"
#     environment:
#       - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#       - GF_AUTH_ANONYMOUS_ENABLED=true
#       - GF_AUTH_BASIC_ENABLED=false
#       - GF_SERVER_SERVE_FROM_SUB_PATH=true
#     volumes:
#       - ./dashboards:/var/lib/grafana/dashboards
#       - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
#       - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

#   chronograf:
#     image: chronograf:1.8
#     ports:
#       - "8888:8888"
#     environment:
#       - INFLUXDB_URL=http://influxdb:8086
#       - INFLUXDB_USERNAME=root
#       - INFLUXDB_PASSWORD=root
#       - INFLUXDB_SKIP_VERIFY=true
#     depends_on:
#       - influxdb
#     networks:
#       - k6  

#   k6:
#     image: grafana/k6
# #    entrypoint: /bin/sh
# #    user: root
#     networks:
#       - k6
#     ports:
#       - "6565:6565"
#     environment:
#       - K6_OUT=influxdb=http://influxdb:8086/k6
#     volumes:
#       - ./scripts:/scripts